name: Mulit-Environment CI/CD

on: [push]

jobs: 
  test-suite:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Automated Tests
        run: |
          echo "Running Unit & Integration Tests"
          sleep 3
          echo "Test Passed"

  onebox:
    runs-on: ubuntu-latest
    needs: test-suite
    steps: 
      - name: Deploy to OneBox
        run: |
          echo "Deploying to OneBox environment"
          sleep 3
          echo "OneBox Deployment Successful"

  staging:
    runs-on: ubuntu-latest
    needs: onebox
    steps:
      - name: Deploy to staging (Beta / Gamma)
        run: |
          echo "Deploying to Staging"
          sleep 3 
          echo "Staging Deployment Successful"

  production:
    runs-on: ubuntu-latest
    needs: staging
    steps:
      - name: Deploy to Production
        run: |
          echo "Deploying to Production"
          sleep 3 
          echo "Production Deployment Successful"
